services:
  httpd:
    #image: php:8.1.32-apache-bookworm
    build:
      context: api
      dockerfile: ../Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./build:/var/www/html/fungi/
      - ./.htaccess:/var/www/html/fungi/.htaccess
      - ./api:/var/www/html/fungi/api
